# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/180/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/180/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /d/skale-consensus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /d/skale-consensus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/180/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/180/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/180/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/180/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/180/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/180/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/180/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/180/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /d/skale-consensus && $(CMAKE_COMMAND) -E cmake_progress_start /d/skale-consensus/CMakeFiles /d/skale-consensus/libBLS//CMakeFiles/progress.marks
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/all
	$(CMAKE_COMMAND) -E cmake_progress_start /d/skale-consensus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /d/skale-consensus && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
libBLS/CMakeFiles/hash_g1.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/hash_g1.dir/rule
.PHONY : libBLS/CMakeFiles/hash_g1.dir/rule

# Convenience name for target.
hash_g1: libBLS/CMakeFiles/hash_g1.dir/rule
.PHONY : hash_g1

# fast build rule for target.
hash_g1/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/hash_g1.dir/build.make libBLS/CMakeFiles/hash_g1.dir/build
.PHONY : hash_g1/fast

# Convenience name for target.
libBLS/CMakeFiles/dkg_glue.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/dkg_glue.dir/rule
.PHONY : libBLS/CMakeFiles/dkg_glue.dir/rule

# Convenience name for target.
dkg_glue: libBLS/CMakeFiles/dkg_glue.dir/rule
.PHONY : dkg_glue

# fast build rule for target.
dkg_glue/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_glue.dir/build.make libBLS/CMakeFiles/dkg_glue.dir/build
.PHONY : dkg_glue/fast

# Convenience name for target.
libBLS/CMakeFiles/verify_bls.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/verify_bls.dir/rule
.PHONY : libBLS/CMakeFiles/verify_bls.dir/rule

# Convenience name for target.
verify_bls: libBLS/CMakeFiles/verify_bls.dir/rule
.PHONY : verify_bls

# fast build rule for target.
verify_bls/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/verify_bls.dir/build.make libBLS/CMakeFiles/verify_bls.dir/build
.PHONY : verify_bls/fast

# Convenience name for target.
libBLS/CMakeFiles/bls_glue.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/bls_glue.dir/rule
.PHONY : libBLS/CMakeFiles/bls_glue.dir/rule

# Convenience name for target.
bls_glue: libBLS/CMakeFiles/bls_glue.dir/rule
.PHONY : bls_glue

# fast build rule for target.
bls_glue/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_glue.dir/build.make libBLS/CMakeFiles/bls_glue.dir/build
.PHONY : bls_glue/fast

# Convenience name for target.
libBLS/CMakeFiles/sign_bls.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/sign_bls.dir/rule
.PHONY : libBLS/CMakeFiles/sign_bls.dir/rule

# Convenience name for target.
sign_bls: libBLS/CMakeFiles/sign_bls.dir/rule
.PHONY : sign_bls

# fast build rule for target.
sign_bls/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/sign_bls.dir/build.make libBLS/CMakeFiles/sign_bls.dir/build
.PHONY : sign_bls/fast

# Convenience name for target.
libBLS/CMakeFiles/utils_unit_test.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/utils_unit_test.dir/rule
.PHONY : libBLS/CMakeFiles/utils_unit_test.dir/rule

# Convenience name for target.
utils_unit_test: libBLS/CMakeFiles/utils_unit_test.dir/rule
.PHONY : utils_unit_test

# fast build rule for target.
utils_unit_test/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/utils_unit_test.dir/build.make libBLS/CMakeFiles/utils_unit_test.dir/build
.PHONY : utils_unit_test/fast

# Convenience name for target.
libBLS/CMakeFiles/dkg_keygen.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/dkg_keygen.dir/rule
.PHONY : libBLS/CMakeFiles/dkg_keygen.dir/rule

# Convenience name for target.
dkg_keygen: libBLS/CMakeFiles/dkg_keygen.dir/rule
.PHONY : dkg_keygen

# fast build rule for target.
dkg_keygen/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_keygen.dir/build.make libBLS/CMakeFiles/dkg_keygen.dir/build
.PHONY : dkg_keygen/fast

# Convenience name for target.
libBLS/CMakeFiles/dkg_unit_test.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/dkg_unit_test.dir/rule
.PHONY : libBLS/CMakeFiles/dkg_unit_test.dir/rule

# Convenience name for target.
dkg_unit_test: libBLS/CMakeFiles/dkg_unit_test.dir/rule
.PHONY : dkg_unit_test

# fast build rule for target.
dkg_unit_test/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_unit_test.dir/build.make libBLS/CMakeFiles/dkg_unit_test.dir/build
.PHONY : dkg_unit_test/fast

# Convenience name for target.
libBLS/CMakeFiles/bls-format.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/bls-format.dir/rule
.PHONY : libBLS/CMakeFiles/bls-format.dir/rule

# Convenience name for target.
bls-format: libBLS/CMakeFiles/bls-format.dir/rule
.PHONY : bls-format

# fast build rule for target.
bls-format/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls-format.dir/build.make libBLS/CMakeFiles/bls-format.dir/build
.PHONY : bls-format/fast

# Convenience name for target.
libBLS/CMakeFiles/bls-format-check-changed.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/bls-format-check-changed.dir/rule
.PHONY : libBLS/CMakeFiles/bls-format-check-changed.dir/rule

# Convenience name for target.
bls-format-check-changed: libBLS/CMakeFiles/bls-format-check-changed.dir/rule
.PHONY : bls-format-check-changed

# fast build rule for target.
bls-format-check-changed/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls-format-check-changed.dir/build.make libBLS/CMakeFiles/bls-format-check-changed.dir/build
.PHONY : bls-format-check-changed/fast

# Convenience name for target.
libBLS/CMakeFiles/bls.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/bls.dir/rule
.PHONY : libBLS/CMakeFiles/bls.dir/rule

# Convenience name for target.
bls: libBLS/CMakeFiles/bls.dir/rule
.PHONY : bls

# fast build rule for target.
bls/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/build
.PHONY : bls/fast

# Convenience name for target.
libBLS/CMakeFiles/bls_unit_test.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/bls_unit_test.dir/rule
.PHONY : libBLS/CMakeFiles/bls_unit_test.dir/rule

# Convenience name for target.
bls_unit_test: libBLS/CMakeFiles/bls_unit_test.dir/rule
.PHONY : bls_unit_test

# fast build rule for target.
bls_unit_test/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_unit_test.dir/build.make libBLS/CMakeFiles/bls_unit_test.dir/build
.PHONY : bls_unit_test/fast

# Convenience name for target.
libBLS/CMakeFiles/dkg_attack.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/dkg_attack.dir/rule
.PHONY : libBLS/CMakeFiles/dkg_attack.dir/rule

# Convenience name for target.
dkg_attack: libBLS/CMakeFiles/dkg_attack.dir/rule
.PHONY : dkg_attack

# fast build rule for target.
dkg_attack/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_attack.dir/build.make libBLS/CMakeFiles/dkg_attack.dir/build
.PHONY : dkg_attack/fast

# Convenience name for target.
libBLS/CMakeFiles/all_bls_tests.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/all_bls_tests.dir/rule
.PHONY : libBLS/CMakeFiles/all_bls_tests.dir/rule

# Convenience name for target.
all_bls_tests: libBLS/CMakeFiles/all_bls_tests.dir/rule
.PHONY : all_bls_tests

# fast build rule for target.
all_bls_tests/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/all_bls_tests.dir/build.make libBLS/CMakeFiles/all_bls_tests.dir/build
.PHONY : all_bls_tests/fast

# Convenience name for target.
libBLS/CMakeFiles/bls_test.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/bls_test.dir/rule
.PHONY : libBLS/CMakeFiles/bls_test.dir/rule

# Convenience name for target.
bls_test: libBLS/CMakeFiles/bls_test.dir/rule
.PHONY : bls_test

# fast build rule for target.
bls_test/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_test.dir/build.make libBLS/CMakeFiles/bls_test.dir/build
.PHONY : bls_test/fast

# Convenience name for target.
libBLS/CMakeFiles/generate_key_system.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/generate_key_system.dir/rule
.PHONY : libBLS/CMakeFiles/generate_key_system.dir/rule

# Convenience name for target.
generate_key_system: libBLS/CMakeFiles/generate_key_system.dir/rule
.PHONY : generate_key_system

# fast build rule for target.
generate_key_system/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/generate_key_system.dir/build.make libBLS/CMakeFiles/generate_key_system.dir/build
.PHONY : generate_key_system/fast

# Convenience name for target.
libBLS/CMakeFiles/bls-format-check.dir/rule:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libBLS/CMakeFiles/bls-format-check.dir/rule
.PHONY : libBLS/CMakeFiles/bls-format-check.dir/rule

# Convenience name for target.
bls-format-check: libBLS/CMakeFiles/bls-format-check.dir/rule
.PHONY : bls-format-check

# fast build rule for target.
bls-format-check/fast:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls-format-check.dir/build.make libBLS/CMakeFiles/bls-format-check.dir/build
.PHONY : bls-format-check/fast

bls/BLSPrivateKey.o: bls/BLSPrivateKey.cpp.o
.PHONY : bls/BLSPrivateKey.o

# target to build an object file
bls/BLSPrivateKey.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPrivateKey.cpp.o
.PHONY : bls/BLSPrivateKey.cpp.o

bls/BLSPrivateKey.i: bls/BLSPrivateKey.cpp.i
.PHONY : bls/BLSPrivateKey.i

# target to preprocess a source file
bls/BLSPrivateKey.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPrivateKey.cpp.i
.PHONY : bls/BLSPrivateKey.cpp.i

bls/BLSPrivateKey.s: bls/BLSPrivateKey.cpp.s
.PHONY : bls/BLSPrivateKey.s

# target to generate assembly for a file
bls/BLSPrivateKey.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPrivateKey.cpp.s
.PHONY : bls/BLSPrivateKey.cpp.s

bls/BLSPrivateKeyShare.o: bls/BLSPrivateKeyShare.cpp.o
.PHONY : bls/BLSPrivateKeyShare.o

# target to build an object file
bls/BLSPrivateKeyShare.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPrivateKeyShare.cpp.o
.PHONY : bls/BLSPrivateKeyShare.cpp.o

bls/BLSPrivateKeyShare.i: bls/BLSPrivateKeyShare.cpp.i
.PHONY : bls/BLSPrivateKeyShare.i

# target to preprocess a source file
bls/BLSPrivateKeyShare.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPrivateKeyShare.cpp.i
.PHONY : bls/BLSPrivateKeyShare.cpp.i

bls/BLSPrivateKeyShare.s: bls/BLSPrivateKeyShare.cpp.s
.PHONY : bls/BLSPrivateKeyShare.s

# target to generate assembly for a file
bls/BLSPrivateKeyShare.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPrivateKeyShare.cpp.s
.PHONY : bls/BLSPrivateKeyShare.cpp.s

bls/BLSPublicKey.o: bls/BLSPublicKey.cpp.o
.PHONY : bls/BLSPublicKey.o

# target to build an object file
bls/BLSPublicKey.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPublicKey.cpp.o
.PHONY : bls/BLSPublicKey.cpp.o

bls/BLSPublicKey.i: bls/BLSPublicKey.cpp.i
.PHONY : bls/BLSPublicKey.i

# target to preprocess a source file
bls/BLSPublicKey.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPublicKey.cpp.i
.PHONY : bls/BLSPublicKey.cpp.i

bls/BLSPublicKey.s: bls/BLSPublicKey.cpp.s
.PHONY : bls/BLSPublicKey.s

# target to generate assembly for a file
bls/BLSPublicKey.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPublicKey.cpp.s
.PHONY : bls/BLSPublicKey.cpp.s

bls/BLSPublicKeyShare.o: bls/BLSPublicKeyShare.cpp.o
.PHONY : bls/BLSPublicKeyShare.o

# target to build an object file
bls/BLSPublicKeyShare.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPublicKeyShare.cpp.o
.PHONY : bls/BLSPublicKeyShare.cpp.o

bls/BLSPublicKeyShare.i: bls/BLSPublicKeyShare.cpp.i
.PHONY : bls/BLSPublicKeyShare.i

# target to preprocess a source file
bls/BLSPublicKeyShare.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPublicKeyShare.cpp.i
.PHONY : bls/BLSPublicKeyShare.cpp.i

bls/BLSPublicKeyShare.s: bls/BLSPublicKeyShare.cpp.s
.PHONY : bls/BLSPublicKeyShare.s

# target to generate assembly for a file
bls/BLSPublicKeyShare.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSPublicKeyShare.cpp.s
.PHONY : bls/BLSPublicKeyShare.cpp.s

bls/BLSSigShare.o: bls/BLSSigShare.cpp.o
.PHONY : bls/BLSSigShare.o

# target to build an object file
bls/BLSSigShare.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSigShare.cpp.o
.PHONY : bls/BLSSigShare.cpp.o

bls/BLSSigShare.i: bls/BLSSigShare.cpp.i
.PHONY : bls/BLSSigShare.i

# target to preprocess a source file
bls/BLSSigShare.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSigShare.cpp.i
.PHONY : bls/BLSSigShare.cpp.i

bls/BLSSigShare.s: bls/BLSSigShare.cpp.s
.PHONY : bls/BLSSigShare.s

# target to generate assembly for a file
bls/BLSSigShare.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSigShare.cpp.s
.PHONY : bls/BLSSigShare.cpp.s

bls/BLSSigShareSet.o: bls/BLSSigShareSet.cpp.o
.PHONY : bls/BLSSigShareSet.o

# target to build an object file
bls/BLSSigShareSet.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSigShareSet.cpp.o
.PHONY : bls/BLSSigShareSet.cpp.o

bls/BLSSigShareSet.i: bls/BLSSigShareSet.cpp.i
.PHONY : bls/BLSSigShareSet.i

# target to preprocess a source file
bls/BLSSigShareSet.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSigShareSet.cpp.i
.PHONY : bls/BLSSigShareSet.cpp.i

bls/BLSSigShareSet.s: bls/BLSSigShareSet.cpp.s
.PHONY : bls/BLSSigShareSet.s

# target to generate assembly for a file
bls/BLSSigShareSet.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSigShareSet.cpp.s
.PHONY : bls/BLSSigShareSet.cpp.s

bls/BLSSignature.o: bls/BLSSignature.cpp.o
.PHONY : bls/BLSSignature.o

# target to build an object file
bls/BLSSignature.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSignature.cpp.o
.PHONY : bls/BLSSignature.cpp.o

bls/BLSSignature.i: bls/BLSSignature.cpp.i
.PHONY : bls/BLSSignature.i

# target to preprocess a source file
bls/BLSSignature.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSignature.cpp.i
.PHONY : bls/BLSSignature.cpp.i

bls/BLSSignature.s: bls/BLSSignature.cpp.s
.PHONY : bls/BLSSignature.s

# target to generate assembly for a file
bls/BLSSignature.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/BLSSignature.cpp.s
.PHONY : bls/BLSSignature.cpp.s

bls/bls.o: bls/bls.cpp.o
.PHONY : bls/bls.o

# target to build an object file
bls/bls.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/bls.cpp.o
.PHONY : bls/bls.cpp.o

bls/bls.i: bls/bls.cpp.i
.PHONY : bls/bls.i

# target to preprocess a source file
bls/bls.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/bls.cpp.i
.PHONY : bls/bls.cpp.i

bls/bls.s: bls/bls.cpp.s
.PHONY : bls/bls.s

# target to generate assembly for a file
bls/bls.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/bls/bls.cpp.s
.PHONY : bls/bls.cpp.s

dkg/DKGBLSSecret.o: dkg/DKGBLSSecret.cpp.o
.PHONY : dkg/DKGBLSSecret.o

# target to build an object file
dkg/DKGBLSSecret.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/DKGBLSSecret.cpp.o
.PHONY : dkg/DKGBLSSecret.cpp.o

dkg/DKGBLSSecret.i: dkg/DKGBLSSecret.cpp.i
.PHONY : dkg/DKGBLSSecret.i

# target to preprocess a source file
dkg/DKGBLSSecret.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/DKGBLSSecret.cpp.i
.PHONY : dkg/DKGBLSSecret.cpp.i

dkg/DKGBLSSecret.s: dkg/DKGBLSSecret.cpp.s
.PHONY : dkg/DKGBLSSecret.s

# target to generate assembly for a file
dkg/DKGBLSSecret.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/DKGBLSSecret.cpp.s
.PHONY : dkg/DKGBLSSecret.cpp.s

dkg/DKGBLSWrapper.o: dkg/DKGBLSWrapper.cpp.o
.PHONY : dkg/DKGBLSWrapper.o

# target to build an object file
dkg/DKGBLSWrapper.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/DKGBLSWrapper.cpp.o
.PHONY : dkg/DKGBLSWrapper.cpp.o

dkg/DKGBLSWrapper.i: dkg/DKGBLSWrapper.cpp.i
.PHONY : dkg/DKGBLSWrapper.i

# target to preprocess a source file
dkg/DKGBLSWrapper.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/DKGBLSWrapper.cpp.i
.PHONY : dkg/DKGBLSWrapper.cpp.i

dkg/DKGBLSWrapper.s: dkg/DKGBLSWrapper.cpp.s
.PHONY : dkg/DKGBLSWrapper.s

# target to generate assembly for a file
dkg/DKGBLSWrapper.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/DKGBLSWrapper.cpp.s
.PHONY : dkg/DKGBLSWrapper.cpp.s

dkg/dkg.o: dkg/dkg.cpp.o
.PHONY : dkg/dkg.o

# target to build an object file
dkg/dkg.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/dkg.cpp.o
.PHONY : dkg/dkg.cpp.o

dkg/dkg.i: dkg/dkg.cpp.i
.PHONY : dkg/dkg.i

# target to preprocess a source file
dkg/dkg.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/dkg.cpp.i
.PHONY : dkg/dkg.cpp.i

dkg/dkg.s: dkg/dkg.cpp.s
.PHONY : dkg/dkg.s

# target to generate assembly for a file
dkg/dkg.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/dkg/dkg.cpp.s
.PHONY : dkg/dkg.cpp.s

test/dkg_attack.o: test/dkg_attack.cpp.o
.PHONY : test/dkg_attack.o

# target to build an object file
test/dkg_attack.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_attack.dir/build.make libBLS/CMakeFiles/dkg_attack.dir/test/dkg_attack.cpp.o
.PHONY : test/dkg_attack.cpp.o

test/dkg_attack.i: test/dkg_attack.cpp.i
.PHONY : test/dkg_attack.i

# target to preprocess a source file
test/dkg_attack.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_attack.dir/build.make libBLS/CMakeFiles/dkg_attack.dir/test/dkg_attack.cpp.i
.PHONY : test/dkg_attack.cpp.i

test/dkg_attack.s: test/dkg_attack.cpp.s
.PHONY : test/dkg_attack.s

# target to generate assembly for a file
test/dkg_attack.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_attack.dir/build.make libBLS/CMakeFiles/dkg_attack.dir/test/dkg_attack.cpp.s
.PHONY : test/dkg_attack.cpp.s

test/test_bls.o: test/test_bls.cpp.o
.PHONY : test/test_bls.o

# target to build an object file
test/test_bls.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_test.dir/build.make libBLS/CMakeFiles/bls_test.dir/test/test_bls.cpp.o
.PHONY : test/test_bls.cpp.o

test/test_bls.i: test/test_bls.cpp.i
.PHONY : test/test_bls.i

# target to preprocess a source file
test/test_bls.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_test.dir/build.make libBLS/CMakeFiles/bls_test.dir/test/test_bls.cpp.i
.PHONY : test/test_bls.cpp.i

test/test_bls.s: test/test_bls.cpp.s
.PHONY : test/test_bls.s

# target to generate assembly for a file
test/test_bls.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_test.dir/build.make libBLS/CMakeFiles/bls_test.dir/test/test_bls.cpp.s
.PHONY : test/test_bls.cpp.s

test/unit_tests_bls.o: test/unit_tests_bls.cpp.o
.PHONY : test/unit_tests_bls.o

# target to build an object file
test/unit_tests_bls.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_unit_test.dir/build.make libBLS/CMakeFiles/bls_unit_test.dir/test/unit_tests_bls.cpp.o
.PHONY : test/unit_tests_bls.cpp.o

test/unit_tests_bls.i: test/unit_tests_bls.cpp.i
.PHONY : test/unit_tests_bls.i

# target to preprocess a source file
test/unit_tests_bls.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_unit_test.dir/build.make libBLS/CMakeFiles/bls_unit_test.dir/test/unit_tests_bls.cpp.i
.PHONY : test/unit_tests_bls.cpp.i

test/unit_tests_bls.s: test/unit_tests_bls.cpp.s
.PHONY : test/unit_tests_bls.s

# target to generate assembly for a file
test/unit_tests_bls.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_unit_test.dir/build.make libBLS/CMakeFiles/bls_unit_test.dir/test/unit_tests_bls.cpp.s
.PHONY : test/unit_tests_bls.cpp.s

test/unit_tests_dkg.o: test/unit_tests_dkg.cpp.o
.PHONY : test/unit_tests_dkg.o

# target to build an object file
test/unit_tests_dkg.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_unit_test.dir/build.make libBLS/CMakeFiles/dkg_unit_test.dir/test/unit_tests_dkg.cpp.o
.PHONY : test/unit_tests_dkg.cpp.o

test/unit_tests_dkg.i: test/unit_tests_dkg.cpp.i
.PHONY : test/unit_tests_dkg.i

# target to preprocess a source file
test/unit_tests_dkg.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_unit_test.dir/build.make libBLS/CMakeFiles/dkg_unit_test.dir/test/unit_tests_dkg.cpp.i
.PHONY : test/unit_tests_dkg.cpp.i

test/unit_tests_dkg.s: test/unit_tests_dkg.cpp.s
.PHONY : test/unit_tests_dkg.s

# target to generate assembly for a file
test/unit_tests_dkg.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_unit_test.dir/build.make libBLS/CMakeFiles/dkg_unit_test.dir/test/unit_tests_dkg.cpp.s
.PHONY : test/unit_tests_dkg.cpp.s

test/unit_tests_utils.o: test/unit_tests_utils.cpp.o
.PHONY : test/unit_tests_utils.o

# target to build an object file
test/unit_tests_utils.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/utils_unit_test.dir/build.make libBLS/CMakeFiles/utils_unit_test.dir/test/unit_tests_utils.cpp.o
.PHONY : test/unit_tests_utils.cpp.o

test/unit_tests_utils.i: test/unit_tests_utils.cpp.i
.PHONY : test/unit_tests_utils.i

# target to preprocess a source file
test/unit_tests_utils.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/utils_unit_test.dir/build.make libBLS/CMakeFiles/utils_unit_test.dir/test/unit_tests_utils.cpp.i
.PHONY : test/unit_tests_utils.cpp.i

test/unit_tests_utils.s: test/unit_tests_utils.cpp.s
.PHONY : test/unit_tests_utils.s

# target to generate assembly for a file
test/unit_tests_utils.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/utils_unit_test.dir/build.make libBLS/CMakeFiles/utils_unit_test.dir/test/unit_tests_utils.cpp.s
.PHONY : test/unit_tests_utils.cpp.s

third_party/cryptlite/base64.o: third_party/cryptlite/base64.cpp.o
.PHONY : third_party/cryptlite/base64.o

# target to build an object file
third_party/cryptlite/base64.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/third_party/cryptlite/base64.cpp.o
.PHONY : third_party/cryptlite/base64.cpp.o

third_party/cryptlite/base64.i: third_party/cryptlite/base64.cpp.i
.PHONY : third_party/cryptlite/base64.i

# target to preprocess a source file
third_party/cryptlite/base64.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/third_party/cryptlite/base64.cpp.i
.PHONY : third_party/cryptlite/base64.cpp.i

third_party/cryptlite/base64.s: third_party/cryptlite/base64.cpp.s
.PHONY : third_party/cryptlite/base64.s

# target to generate assembly for a file
third_party/cryptlite/base64.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/third_party/cryptlite/base64.cpp.s
.PHONY : third_party/cryptlite/base64.cpp.s

tools/bls_glue.o: tools/bls_glue.cpp.o
.PHONY : tools/bls_glue.o

# target to build an object file
tools/bls_glue.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_glue.dir/build.make libBLS/CMakeFiles/bls_glue.dir/tools/bls_glue.cpp.o
.PHONY : tools/bls_glue.cpp.o

tools/bls_glue.i: tools/bls_glue.cpp.i
.PHONY : tools/bls_glue.i

# target to preprocess a source file
tools/bls_glue.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_glue.dir/build.make libBLS/CMakeFiles/bls_glue.dir/tools/bls_glue.cpp.i
.PHONY : tools/bls_glue.cpp.i

tools/bls_glue.s: tools/bls_glue.cpp.s
.PHONY : tools/bls_glue.s

# target to generate assembly for a file
tools/bls_glue.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls_glue.dir/build.make libBLS/CMakeFiles/bls_glue.dir/tools/bls_glue.cpp.s
.PHONY : tools/bls_glue.cpp.s

tools/dkg_glue.o: tools/dkg_glue.cpp.o
.PHONY : tools/dkg_glue.o

# target to build an object file
tools/dkg_glue.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_glue.dir/build.make libBLS/CMakeFiles/dkg_glue.dir/tools/dkg_glue.cpp.o
.PHONY : tools/dkg_glue.cpp.o

tools/dkg_glue.i: tools/dkg_glue.cpp.i
.PHONY : tools/dkg_glue.i

# target to preprocess a source file
tools/dkg_glue.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_glue.dir/build.make libBLS/CMakeFiles/dkg_glue.dir/tools/dkg_glue.cpp.i
.PHONY : tools/dkg_glue.cpp.i

tools/dkg_glue.s: tools/dkg_glue.cpp.s
.PHONY : tools/dkg_glue.s

# target to generate assembly for a file
tools/dkg_glue.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_glue.dir/build.make libBLS/CMakeFiles/dkg_glue.dir/tools/dkg_glue.cpp.s
.PHONY : tools/dkg_glue.cpp.s

tools/dkg_key_gen.o: tools/dkg_key_gen.cpp.o
.PHONY : tools/dkg_key_gen.o

# target to build an object file
tools/dkg_key_gen.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_keygen.dir/build.make libBLS/CMakeFiles/dkg_keygen.dir/tools/dkg_key_gen.cpp.o
.PHONY : tools/dkg_key_gen.cpp.o

tools/dkg_key_gen.i: tools/dkg_key_gen.cpp.i
.PHONY : tools/dkg_key_gen.i

# target to preprocess a source file
tools/dkg_key_gen.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_keygen.dir/build.make libBLS/CMakeFiles/dkg_keygen.dir/tools/dkg_key_gen.cpp.i
.PHONY : tools/dkg_key_gen.cpp.i

tools/dkg_key_gen.s: tools/dkg_key_gen.cpp.s
.PHONY : tools/dkg_key_gen.s

# target to generate assembly for a file
tools/dkg_key_gen.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/dkg_keygen.dir/build.make libBLS/CMakeFiles/dkg_keygen.dir/tools/dkg_key_gen.cpp.s
.PHONY : tools/dkg_key_gen.cpp.s

tools/generate_key_system.o: tools/generate_key_system.cpp.o
.PHONY : tools/generate_key_system.o

# target to build an object file
tools/generate_key_system.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/generate_key_system.dir/build.make libBLS/CMakeFiles/generate_key_system.dir/tools/generate_key_system.cpp.o
.PHONY : tools/generate_key_system.cpp.o

tools/generate_key_system.i: tools/generate_key_system.cpp.i
.PHONY : tools/generate_key_system.i

# target to preprocess a source file
tools/generate_key_system.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/generate_key_system.dir/build.make libBLS/CMakeFiles/generate_key_system.dir/tools/generate_key_system.cpp.i
.PHONY : tools/generate_key_system.cpp.i

tools/generate_key_system.s: tools/generate_key_system.cpp.s
.PHONY : tools/generate_key_system.s

# target to generate assembly for a file
tools/generate_key_system.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/generate_key_system.dir/build.make libBLS/CMakeFiles/generate_key_system.dir/tools/generate_key_system.cpp.s
.PHONY : tools/generate_key_system.cpp.s

tools/hash_g1.o: tools/hash_g1.cpp.o
.PHONY : tools/hash_g1.o

# target to build an object file
tools/hash_g1.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/hash_g1.dir/build.make libBLS/CMakeFiles/hash_g1.dir/tools/hash_g1.cpp.o
.PHONY : tools/hash_g1.cpp.o

tools/hash_g1.i: tools/hash_g1.cpp.i
.PHONY : tools/hash_g1.i

# target to preprocess a source file
tools/hash_g1.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/hash_g1.dir/build.make libBLS/CMakeFiles/hash_g1.dir/tools/hash_g1.cpp.i
.PHONY : tools/hash_g1.cpp.i

tools/hash_g1.s: tools/hash_g1.cpp.s
.PHONY : tools/hash_g1.s

# target to generate assembly for a file
tools/hash_g1.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/hash_g1.dir/build.make libBLS/CMakeFiles/hash_g1.dir/tools/hash_g1.cpp.s
.PHONY : tools/hash_g1.cpp.s

tools/sign_bls.o: tools/sign_bls.cpp.o
.PHONY : tools/sign_bls.o

# target to build an object file
tools/sign_bls.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/sign_bls.dir/build.make libBLS/CMakeFiles/sign_bls.dir/tools/sign_bls.cpp.o
.PHONY : tools/sign_bls.cpp.o

tools/sign_bls.i: tools/sign_bls.cpp.i
.PHONY : tools/sign_bls.i

# target to preprocess a source file
tools/sign_bls.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/sign_bls.dir/build.make libBLS/CMakeFiles/sign_bls.dir/tools/sign_bls.cpp.i
.PHONY : tools/sign_bls.cpp.i

tools/sign_bls.s: tools/sign_bls.cpp.s
.PHONY : tools/sign_bls.s

# target to generate assembly for a file
tools/sign_bls.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/sign_bls.dir/build.make libBLS/CMakeFiles/sign_bls.dir/tools/sign_bls.cpp.s
.PHONY : tools/sign_bls.cpp.s

tools/utils.o: tools/utils.cpp.o
.PHONY : tools/utils.o

# target to build an object file
tools/utils.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/tools/utils.cpp.o
.PHONY : tools/utils.cpp.o

tools/utils.i: tools/utils.cpp.i
.PHONY : tools/utils.i

# target to preprocess a source file
tools/utils.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/tools/utils.cpp.i
.PHONY : tools/utils.cpp.i

tools/utils.s: tools/utils.cpp.s
.PHONY : tools/utils.s

# target to generate assembly for a file
tools/utils.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/bls.dir/build.make libBLS/CMakeFiles/bls.dir/tools/utils.cpp.s
.PHONY : tools/utils.cpp.s

tools/verify_bls.o: tools/verify_bls.cpp.o
.PHONY : tools/verify_bls.o

# target to build an object file
tools/verify_bls.cpp.o:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/verify_bls.dir/build.make libBLS/CMakeFiles/verify_bls.dir/tools/verify_bls.cpp.o
.PHONY : tools/verify_bls.cpp.o

tools/verify_bls.i: tools/verify_bls.cpp.i
.PHONY : tools/verify_bls.i

# target to preprocess a source file
tools/verify_bls.cpp.i:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/verify_bls.dir/build.make libBLS/CMakeFiles/verify_bls.dir/tools/verify_bls.cpp.i
.PHONY : tools/verify_bls.cpp.i

tools/verify_bls.s: tools/verify_bls.cpp.s
.PHONY : tools/verify_bls.s

# target to generate assembly for a file
tools/verify_bls.cpp.s:
	cd /d/skale-consensus && $(MAKE) $(MAKESILENT) -f libBLS/CMakeFiles/verify_bls.dir/build.make libBLS/CMakeFiles/verify_bls.dir/tools/verify_bls.cpp.s
.PHONY : tools/verify_bls.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... all_bls_tests"
	@echo "... bls-format"
	@echo "... bls-format-check"
	@echo "... bls-format-check-changed"
	@echo "... bls"
	@echo "... bls_glue"
	@echo "... bls_test"
	@echo "... bls_unit_test"
	@echo "... dkg_attack"
	@echo "... dkg_glue"
	@echo "... dkg_keygen"
	@echo "... dkg_unit_test"
	@echo "... generate_key_system"
	@echo "... hash_g1"
	@echo "... sign_bls"
	@echo "... utils_unit_test"
	@echo "... verify_bls"
	@echo "... bls/BLSPrivateKey.o"
	@echo "... bls/BLSPrivateKey.i"
	@echo "... bls/BLSPrivateKey.s"
	@echo "... bls/BLSPrivateKeyShare.o"
	@echo "... bls/BLSPrivateKeyShare.i"
	@echo "... bls/BLSPrivateKeyShare.s"
	@echo "... bls/BLSPublicKey.o"
	@echo "... bls/BLSPublicKey.i"
	@echo "... bls/BLSPublicKey.s"
	@echo "... bls/BLSPublicKeyShare.o"
	@echo "... bls/BLSPublicKeyShare.i"
	@echo "... bls/BLSPublicKeyShare.s"
	@echo "... bls/BLSSigShare.o"
	@echo "... bls/BLSSigShare.i"
	@echo "... bls/BLSSigShare.s"
	@echo "... bls/BLSSigShareSet.o"
	@echo "... bls/BLSSigShareSet.i"
	@echo "... bls/BLSSigShareSet.s"
	@echo "... bls/BLSSignature.o"
	@echo "... bls/BLSSignature.i"
	@echo "... bls/BLSSignature.s"
	@echo "... bls/bls.o"
	@echo "... bls/bls.i"
	@echo "... bls/bls.s"
	@echo "... dkg/DKGBLSSecret.o"
	@echo "... dkg/DKGBLSSecret.i"
	@echo "... dkg/DKGBLSSecret.s"
	@echo "... dkg/DKGBLSWrapper.o"
	@echo "... dkg/DKGBLSWrapper.i"
	@echo "... dkg/DKGBLSWrapper.s"
	@echo "... dkg/dkg.o"
	@echo "... dkg/dkg.i"
	@echo "... dkg/dkg.s"
	@echo "... test/dkg_attack.o"
	@echo "... test/dkg_attack.i"
	@echo "... test/dkg_attack.s"
	@echo "... test/test_bls.o"
	@echo "... test/test_bls.i"
	@echo "... test/test_bls.s"
	@echo "... test/unit_tests_bls.o"
	@echo "... test/unit_tests_bls.i"
	@echo "... test/unit_tests_bls.s"
	@echo "... test/unit_tests_dkg.o"
	@echo "... test/unit_tests_dkg.i"
	@echo "... test/unit_tests_dkg.s"
	@echo "... test/unit_tests_utils.o"
	@echo "... test/unit_tests_utils.i"
	@echo "... test/unit_tests_utils.s"
	@echo "... third_party/cryptlite/base64.o"
	@echo "... third_party/cryptlite/base64.i"
	@echo "... third_party/cryptlite/base64.s"
	@echo "... tools/bls_glue.o"
	@echo "... tools/bls_glue.i"
	@echo "... tools/bls_glue.s"
	@echo "... tools/dkg_glue.o"
	@echo "... tools/dkg_glue.i"
	@echo "... tools/dkg_glue.s"
	@echo "... tools/dkg_key_gen.o"
	@echo "... tools/dkg_key_gen.i"
	@echo "... tools/dkg_key_gen.s"
	@echo "... tools/generate_key_system.o"
	@echo "... tools/generate_key_system.i"
	@echo "... tools/generate_key_system.s"
	@echo "... tools/hash_g1.o"
	@echo "... tools/hash_g1.i"
	@echo "... tools/hash_g1.s"
	@echo "... tools/sign_bls.o"
	@echo "... tools/sign_bls.i"
	@echo "... tools/sign_bls.s"
	@echo "... tools/utils.o"
	@echo "... tools/utils.i"
	@echo "... tools/utils.s"
	@echo "... tools/verify_bls.o"
	@echo "... tools/verify_bls.i"
	@echo "... tools/verify_bls.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /d/skale-consensus && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

